"""Setup wizard — `keycloak-mcp-setup`.

Interviews the operator and emits the least-privilege Keycloak setup plus a
keycloak-mcp.toml. It does NOT call Keycloak and NEVER stores secrets: it only
generates the instructions and config for you to apply.

Output:
  1. Keycloak service-account setup (client + the two roles it needs).
  2. keycloak-mcp.toml (scope + redaction policy; written to disk).
  3. Credential steps (env vars, never the toml).
  4. A ready-to-paste MCP client config block (stdio).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from .config import DEFAULT_REDACT_KEYS, PERSONAL_DATA_KEYS


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        ans = ""
    return ans or default


def _ask_list(prompt: str) -> list[str]:
    raw = _ask(f"{prompt} (comma-separated, blank for none)")
    return [item.strip() for item in raw.split(",") if item.strip()]


def _ask_yes(prompt: str, default_yes: bool = False) -> bool:
    default = "Y/n" if default_yes else "y/N"
    ans = _ask(f"{prompt} ({default})", "").lower()
    if not ans:
        return default_yes
    return ans.startswith("y")


def _toml(group_paths: list[str], redact_keys: list[str], mode: str,
          patterns: list[str]) -> str:
    def fmt(items: list[str]) -> str:
        if not items:
            return "[]"
        body = ",\n".join(f'  "{i}"' for i in items)
        return "[\n" + body + ",\n]"

    return "\n".join([
        "# keycloak-mcp.toml — generated by keycloak-mcp-setup.",
        "# Scope + attribute policy only. Secrets and the base URL live in env",
        "# vars (KC_BASE_URL / KC_REALM / KC_CLIENT_ID / KC_CLIENT_SECRET).",
        "",
        "[scope]",
        "# Group reads are restricted to these subtrees (and everything beneath",
        "# them). Empty = the whole realm, bounded by the service account roles.",
        f"group_paths = {json.dumps(group_paths)}",
        "",
        "[tls]",
        "verify = true",
        '# ca_bundle = "/etc/ssl/certs/internal-ca.pem"',
        "",
        "[redact]",
        "# Attribute keys blanked in every returned record, recursively.",
        "# Whole-key match, case-insensitive, never substring.",
        f'mode = "{mode}"',
        "case_sensitive = false",
        f"keys = {fmt(redact_keys)}",
        f"patterns = {json.dumps(patterns)}",
        "paths = []",
        "",
        "# [attributes]",
        "# Optional stricter allow-list — only these attribute keys survive.",
        '# group_keys = ["costCentre", "serviceTier"]',
        '# user_keys  = ["employeeType", "department"]',
        "",
        "[limits]",
        "page_size   = 100",
        "max_members = 500",
        "max_depth   = 10",
        "timeout     = 30",
    ]) + "\n"


def main() -> None:
    print("keycloak-mcp setup — generates least-privilege Keycloak config.\n")
    print("This wizard does not contact Keycloak and never stores secrets.\n")

    group_paths = _ask_list("Limit reads to which group path(s), e.g. /Engineering")
    print("\nAttribute redaction — which attribute keys must the agent never read?")
    print("  Credential-ish keys (password, secret, token, ...) are always included.")
    include_personal = _ask_yes(
        "  Also redact the personal-data / GDPR starter set "
        "(dateOfBirth, nationalInsuranceNumber, homeAddress, salary, ...)?",
        default_yes=True,
    )
    extra = _ask_list("  Any additional attribute keys specific to your realm")
    patterns = _ask_list("  Any wildcard patterns, e.g. *secret* or urn:ietf:params:scim:*")
    drop = _ask_yes("  Remove redacted keys entirely rather than showing "
                    "'[redacted]'? (hides that the attribute exists at all)")
    mode = "drop" if drop else "redact"

    keys = list(DEFAULT_REDACT_KEYS)
    if include_personal:
        keys += PERSONAL_DATA_KEYS
    keys += [k for k in extra if k not in keys]

    out_path = Path(_ask("\nWrite keycloak-mcp.toml to", "keycloak-mcp.toml"))

    print("\n" + "=" * 72)
    print("1. Keycloak service account (read-only)")
    print("=" * 72)
    print("In the realm you want to read (NOT master):\n")
    print("  a. Clients -> Create client")
    print("       Client ID:            svc-claude-ro   (any name)")
    print("       Client authentication: ON             (confidential client)")
    print("       Authorization:         OFF")
    print("       Authentication flow:   tick ONLY 'Service accounts roles'")
    print("       (untick Standard flow / Direct access grants — no human logs in as this)")
    print("  b. The new client -> Credentials tab -> copy the Client secret.")
    print("  c. The new client -> Service accounts roles -> Assign role ->")
    print("     filter by clients -> realm-management, and assign:")
    print("       - view-users     (reads users, groups and memberships)")
    print("       - query-groups   (lists groups)")
    print("     Assign NOTHING else. In particular never manage-users, manage-realm")
    print("     or realm-admin — this server has no write code path, and the")
    print("     account should not have the right either.")
    print("     If a read still returns 403, add view-realm and retry.")

    print("\n" + "=" * 72)
    print("2. keycloak-mcp.toml")
    print("=" * 72)
    toml_text = _toml(group_paths, keys, mode, patterns)
    if out_path.exists() and not _ask_yes(f"{out_path} exists — overwrite?"):
        print(f"Left {out_path} untouched. Config that would have been written:\n")
        print(toml_text)
    else:
        out_path.write_text(toml_text)
        print(f"Wrote {out_path}:\n")
        print(toml_text)

    print("=" * 72)
    print("3. Credentials (env vars — never the toml)")
    print("=" * 72)
    print("  export KC_BASE_URL='https://sso.example.com'   # no trailing slash")
    print("  export KC_REALM='your-realm'")
    print("  export KC_CLIENT_ID='svc-claude-ro'")
    print("  export KC_CLIENT_SECRET='<client secret from step 1b>'")
    print("\nIf you already source a read-only Keycloak env script for the sibling")
    print("tools, these are the same four variables — reuse it.")

    print("\n" + "=" * 72)
    print("4. Register the server with your MCP client")
    print("=" * 72)
    here = Path(__file__).resolve().parents[2]      # mcp-servers/keycloak
    cfg_path = str(out_path.resolve())

    print("Option A — Claude Code (recommended). Run this command:\n")
    print(
        "  claude mcp add keycloak \\\n"
        "    -e KC_BASE_URL=https://sso.example.com \\\n"
        "    -e KC_REALM=your-realm \\\n"
        "    -e KC_CLIENT_ID=svc-claude-ro \\\n"
        "    -e KC_CLIENT_SECRET='<client secret>' \\\n"
        f"    -e KEYCLOAK_MCP_CONFIG={cfg_path} \\\n"
        f"    -- uv run --directory {here} keycloak-mcp\n"
    )

    print("Option B — paste this block into your MCP config file instead:")
    print("  - Claude Code (global):  ~/.claude.json   under \"mcpServers\"")
    print("  - Claude Desktop:        claude_desktop_config.json")
    print("  - Project-scoped:        .mcp.json in your project root\n")
    block = {
        "mcpServers": {
            "keycloak": {
                "command": "uv",
                "args": ["run", "--directory", str(here), "keycloak-mcp"],
                "env": {
                    "KC_BASE_URL": "https://sso.example.com",
                    "KC_REALM": "your-realm",
                    "KC_CLIENT_ID": "svc-claude-ro",
                    "KC_CLIENT_SECRET": "<client secret>",
                    "KEYCLOAK_MCP_CONFIG": cfg_path,
                },
            }
        }
    }
    print(json.dumps(block, indent=2))

    print("\nThen RESTART your MCP client (the server loads at startup) and the")
    print("keycloak tools appear. Verify with: \"call keycloak_status\" — it echoes")
    print("the scope and the exact list of attribute keys being redacted.")


if __name__ == "__main__":
    sys.exit(main())
