"""Setup wizard — `netbox-mcp-setup`.

Interviews the operator and emits the least-privilege NetBox setup plus a
netbox-mcp.toml. It does NOT call NetBox and NEVER stores secrets (SPEC.md
sec.6): it only generates the instructions and config for you to apply.

Output:
  1. NetBox object-permission constraint JSON (paste into NetBox per model).
  2. netbox-mcp.toml (scope + field policy; written to disk).
  3. Token-creation steps (write_enabled=false, expiry).
  4. A ready-to-paste MCP client config block (stdio).
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from .config import DEFAULT_FIELDS

# Object type -> the NetBox permission object_types label, for the printed guide.
_PERMISSION_OBJECTS = {
    "device": "dcim | device",
    "vm": "virtualization | virtual machine",
    "ip_address": "ipam | IP address",
    "prefix": "ipam | prefix",
    "interface": "dcim | interface",
    "site": "dcim | site",
    "tenant": "tenancy | tenant",
    "rack": "dcim | rack",
}


def _ask(prompt: str, default: str = "") -> str:
    suffix = f" [{default}]" if default else ""
    try:
        ans = input(f"{prompt}{suffix}: ").strip()
    except EOFError:
        ans = ""
    return ans or default


def _ask_list(prompt: str) -> list[str]:
    raw = _ask(f"{prompt} (comma-separated, blank for none)")
    return [item.strip() for item in raw.split(",") if item.strip()]


def _constraint(tenants: list[str], sites: list[str]) -> dict:
    """Build a NetBox permission constraint from the chosen scope. Multiple
    values use the __in style NetBox understands via list values."""
    constraint: dict = {}
    if tenants:
        constraint["tenant__slug"] = tenants if len(tenants) > 1 else tenants[0]
    if sites:
        constraint["site__slug"] = sites if len(sites) > 1 else sites[0]
    return constraint


def _toml(tenants: list[str], sites: list[str], cc_in_lists: bool) -> str:
    lines: list[str] = [
        "# netbox-mcp.toml — generated by netbox-mcp-setup.",
        "# Scope + field policy only. Secrets/URL live in env vars, never here.",
        "",
        "[scope]",
        f"tenants = {json.dumps(tenants)}",
        f"sites = {json.dumps(sites)}",
        "",
        "[config_context]",
        f"in_lists = {str(cc_in_lists).lower()}  # render config_context in list_* by default",
        "",
        "# [custom_fields]",
        '# keys = ["owner", "service_tier"]  # restrict custom_fields to these keys',
        "",
        "# Field allow-sets default to sensible per-object sets baked into the",
        "# server. Uncomment to override any object explicitly:",
    ]
    # Show one worked example; the rest follow the same shape.
    obj, fields = next(iter(DEFAULT_FIELDS.items()))
    lines.append("# [fields]")
    lines.append(f"# {obj} = {json.dumps(fields)}")
    return "\n".join(lines) + "\n"


def main() -> None:
    print("netbox-mcp setup — generates least-privilege NetBox config.\n")
    print("This wizard does not contact NetBox and never stores secrets.\n")

    tenants = _ask_list("Limit to which tenant slug(s)")
    sites = _ask_list("Limit to which site slug(s)")
    cc_default = _ask("Render config_context in list_* by default? (y/N)", "N").lower().startswith("y")
    out_path = Path(_ask("Write netbox-mcp.toml to", "netbox-mcp.toml"))

    constraint = _constraint(tenants, sites)

    print("\n" + "=" * 70)
    print("1. NetBox object permission(s)")
    print("=" * 70)
    print("Create a service user (e.g. svc-claude-ro) with NO login need, then")
    print("add ONE permission per object below — Actions: VIEW only — assigned")
    print("to that user. Paste this JSON into each permission's Constraints box:\n")
    print(json.dumps(constraint, indent=2) if constraint else "{}   (no row scope — exposes all rows; tighten this!)")
    print("\nApply the same constraint to these object types:")
    for label in _PERMISSION_OBJECTS.values():
        print(f"  - {label}")

    print("\n" + "=" * 70)
    print("2. netbox-mcp.toml")
    print("=" * 70)
    toml_text = _toml(tenants, sites, cc_default)
    out_path.write_text(toml_text)
    print(f"Wrote {out_path}:\n")
    print(toml_text)

    print("=" * 70)
    print("3. API token")
    print("=" * 70)
    print("Admin -> API Tokens -> Add, for the service user:")
    print("  - Write enabled: UNCHECKED  (read-only — a hard guarantee)")
    print("  - Set an expiry.")
    print("  - Copy the token into the NETBOX_TOKEN_RO env var (NOT the toml).")

    print("\n" + "=" * 70)
    print("4. Register the server with your MCP client")
    print("=" * 70)
    here = Path(__file__).resolve().parents[2]  # mcp-servers/netbox
    cfg_path = str(out_path.resolve())

    print("Fill in NETBOX_URL and your read-only token, then use EITHER option.\n")

    print("Option A -- Claude Code (recommended). Run this command:\n")
    print(
        "  claude mcp add netbox \\\n"
        "    -e NETBOX_URL=https://netbox.example.com \\\n"
        "    -e NETBOX_TOKEN_RO=<read-only token> \\\n"
        f"    -e NETBOX_MCP_CONFIG={cfg_path} \\\n"
        f"    -- uv run --directory {here} netbox-mcp\n"
    )

    print("Option B -- paste this block into your MCP config file instead:")
    print("  - Claude Code (global):  ~/.claude.json   under \"mcpServers\"")
    print("  - Claude Desktop:        claude_desktop_config.json")
    print("  - Project-scoped:        .mcp.json in your project root\n")
    block = {
        "mcpServers": {
            "netbox": {
                "command": "uv",
                "args": ["run", "--directory", str(here), "netbox-mcp"],
                "env": {
                    "NETBOX_URL": "https://netbox.example.com",
                    "NETBOX_TOKEN_RO": "<read-only token>",
                    "NETBOX_MCP_CONFIG": cfg_path,
                },
            }
        }
    }
    print(json.dumps(block, indent=2))

    print("\nThen RESTART your MCP client (the server loads at startup) and the")
    print("netbox_* tools appear. Verify with: \"call netbox_status\".")


if __name__ == "__main__":
    sys.exit(main())
